prepare:
  split: 640
  step: 50
 

featurize:
  threshold_area: 10
  ngrams: 1


evaluate:
  lower_green: [21, 103, 70]
  upper_green: [117, 255,255]

cluster:
  num_clusters_X: 6
  num_clusters_Y: 10

